#!/bin/sh
set -e
# Remove stale unit file from old install location so systemd
# does not pick up a stale copy ahead of the new one.
rm -f /lib/systemd/system/victron-ve-direct.service
#DEBHELPER#
exit 0
